FROM confluentinc/cp-kafka-connect-base
RUN wget https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-jdbc/versions/10.0.0/confluentinc-kafka-connect-jdbc-10.0.0.zip 
RUN ls -l /tmp
RUN confluent-hub install --no-prompt confluentinc-kafka-connect-jdbc-10.0.0.zip 